/**
 * Lightweight, hand-rolled Vue store
 * 
 * @see https://vuedose.tips/creating-a-store-without-vuex-in-vue-js-2-6
 */

import Vue from "vue"

const store = Vue.observable({
    tasks: [{ "id": 1, "due_date": null, "description": "transform one-to-one vortals", "is_flaged": null, "project": "vacation" },
    { "id": 2, "due_date": null, "description": "innovate dynamic partnerships", "is_flaged": null, "project": "inbox" },
    { "id": 3, "due_date": null, "description": "matrix end-to-end markets", "is_flaged": false, "project": "inbox" },
    { "id": 4, "due_date": null, "description": "enable synergistic interfaces", "is_flaged": null, "project": "reminders" },
    { "id": 5, "due_date": null, "description": "recontextualize robust eyeballs", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 6, "due_date": null, "description": "whiteboard impactful metrics", "is_flaged": false, "project": "kitchen_remodel" },
    { "id": 7, "due_date": null, "description": "synergize compelling technologies", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 8, "due_date": null, "description": "brand killer deliverables", "is_flaged": null, "project": "groceries" },
    { "id": 9, "due_date": null, "description": "aggregate distributed infomediaries", "is_flaged": null, "project": "reminders" },
    { "id": 10, "due_date": null, "description": "reintermediate sticky functionalities", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 11, "due_date": null, "description": "mesh ubiquitous schemas", "is_flaged": null, "project": "inbox" },
    { "id": 12, "due_date": null, "description": "revolutionize 24/7 interfaces", "is_flaged": null, "project": "groceries" },
    { "id": 13, "due_date": null, "description": "incentivize wireless models", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 14, "due_date": null, "description": "evolve leading-edge metrics", "is_flaged": null, "project": "groceries" },
    { "id": 15, "due_date": null, "description": "iterate proactive interfaces", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 16, "due_date": null, "description": "incentivize plug-and-play e-tailers", "is_flaged": null, "project": "vacation" },
    { "id": 17, "due_date": null, "description": "architect compelling models", "is_flaged": null, "project": "reminders" },
    { "id": 18, "due_date": null, "description": "synergize collaborative content", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 19, "due_date": null, "description": "exploit transparent schemas", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 20, "due_date": null, "description": "incentivize e-business ROI", "is_flaged": null, "project": "vacation" },
    { "id": 21, "due_date": null, "description": "redefine enterprise infrastructures", "is_flaged": null, "project": "groceries" },
    { "id": 22, "due_date": "2022-11-22 13:14:17", "description": "seize B2B e-commerce", "is_flaged": true, "project": "groceries" },
    { "id": 23, "due_date": null, "description": "leverage clicks-and-mortar applications", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 24, "due_date": null, "description": "orchestrate leading-edge web-readiness", "is_flaged": null, "project": "groceries" },
    { "id": 25, "due_date": null, "description": "incentivize best-of-breed synergies", "is_flaged": null, "project": "reminders" },
    { "id": 26, "due_date": null, "description": "scale user-centric deliverables", "is_flaged": true, "project": "groceries" },
    { "id": 27, "due_date": "2022-12-05 01:21:29", "description": "morph next-generation e-markets", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 28, "due_date": null, "description": "reintermediate turn-key communities", "is_flaged": null, "project": "vacation" },
    { "id": 29, "due_date": null, "description": "synergize world-class e-business", "is_flaged": null, "project": "groceries" },
    { "id": 30, "due_date": null, "description": "drive global relationships", "is_flaged": null, "project": "inbox" },
    { "id": 31, "due_date": "2022-12-07 13:46:20", "description": "matrix plug-and-play technologies", "is_flaged": null, "project": "groceries" },
    { "id": 32, "due_date": null, "description": "reinvent proactive infrastructures", "is_flaged": null, "project": "inbox" },
    { "id": 33, "due_date": null, "description": "iterate B2B technologies", "is_flaged": null, "project": "inbox" },
    { "id": 34, "due_date": null, "description": "expedite scalable technologies", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 35, "due_date": null, "description": "integrate real-time markets", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 36, "due_date": null, "description": "reintermediate clicks-and-mortar paradigms", "is_flaged": null, "project": "inbox" },
    { "id": 37, "due_date": null, "description": "utilize end-to-end ROI", "is_flaged": null, "project": "reminders" },
    { "id": 38, "due_date": null, "description": "integrate seamless e-business", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 39, "due_date": null, "description": "iterate rich initiatives", "is_flaged": null, "project": "inbox" },
    { "id": 40, "due_date": "2022-11-13 10:32:15", "description": "integrate next-generation experiences", "is_flaged": null, "project": "vacation" },
    { "id": 41, "due_date": null, "description": "whiteboard seamless web services", "is_flaged": false, "project": "groceries" },
    { "id": 42, "due_date": null, "description": "cultivate real-time convergence", "is_flaged": null, "project": "vacation" },
    { "id": 43, "due_date": null, "description": "optimize leading-edge content", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 44, "due_date": null, "description": "embrace intuitive e-services", "is_flaged": null, "project": "inbox" },
    { "id": 45, "due_date": null, "description": "target end-to-end partnerships", "is_flaged": null, "project": "reminders" },
    { "id": 46, "due_date": null, "description": "reinvent out-of-the-box infrastructures", "is_flaged": null, "project": "inbox" },
    { "id": 47, "due_date": null, "description": "redefine cross-media web services", "is_flaged": false, "project": "groceries" },
    { "id": 48, "due_date": null, "description": "visualize impactful experiences", "is_flaged": null, "project": "groceries" },
    { "id": 49, "due_date": null, "description": "exploit cross-media deliverables", "is_flaged": false, "project": "kitchen_remodel" },
    { "id": 50, "due_date": null, "description": "matrix one-to-one paradigms", "is_flaged": false, "project": "groceries" },
    { "id": 51, "due_date": null, "description": "exploit open-source convergence", "is_flaged": null, "project": "inbox" },
    { "id": 52, "due_date": null, "description": "recontextualize holistic content", "is_flaged": null, "project": "inbox" },
    { "id": 53, "due_date": null, "description": "implement holistic e-services", "is_flaged": null, "project": "vacation" },
    { "id": 54, "due_date": null, "description": "mesh B2B metrics", "is_flaged": null, "project": "groceries" },
    { "id": 55, "due_date": null, "description": "incubate out-of-the-box action-items", "is_flaged": true, "project": "reminders" },
    { "id": 56, "due_date": null, "description": "implement customized e-commerce", "is_flaged": null, "project": "inbox" },
    { "id": 57, "due_date": null, "description": "transition viral ROI", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 58, "due_date": null, "description": "benchmark robust users", "is_flaged": null, "project": "inbox" },
    { "id": 59, "due_date": null, "description": "matrix real-time eyeballs", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 60, "due_date": "2022-12-10 06:06:57", "description": "whiteboard cross-media applications", "is_flaged": false, "project": "kitchen_remodel" },
    { "id": 61, "due_date": null, "description": "exploit one-to-one technologies", "is_flaged": null, "project": "groceries" },
    { "id": 62, "due_date": null, "description": "unleash distributed e-commerce", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 63, "due_date": null, "description": "benchmark holistic e-services", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 64, "due_date": null, "description": "enhance end-to-end niches", "is_flaged": false, "project": "kitchen_remodel" },
    { "id": 65, "due_date": null, "description": "empower customized content", "is_flaged": null, "project": "inbox" },
    { "id": 66, "due_date": null, "description": "drive synergistic solutions", "is_flaged": null, "project": "groceries" },
    { "id": 67, "due_date": null, "description": "evolve interactive functionalities", "is_flaged": null, "project": "groceries" },
    { "id": 68, "due_date": null, "description": "e-enable interactive web services", "is_flaged": true, "project": "kitchen_remodel" },
    { "id": 69, "due_date": null, "description": "synergize out-of-the-box e-tailers", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 70, "due_date": null, "description": "grow 24/7 infomediaries", "is_flaged": null, "project": "vacation" },
    { "id": 71, "due_date": null, "description": "mesh sticky solutions", "is_flaged": null, "project": "reminders" },
    { "id": 72, "due_date": null, "description": "recontextualize enterprise web services", "is_flaged": true, "project": "inbox" },
    { "id": 73, "due_date": null, "description": "productize real-time solutions", "is_flaged": null, "project": "groceries" },
    { "id": 74, "due_date": null, "description": "monetize scalable networks", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 75, "due_date": null, "description": "architect B2B eyeballs", "is_flaged": false, "project": "vacation" },
    { "id": 76, "due_date": null, "description": "implement one-to-one mindshare", "is_flaged": null, "project": "groceries" },
    { "id": 77, "due_date": null, "description": "target impactful infomediaries", "is_flaged": null, "project": "vacation" },
    { "id": 78, "due_date": null, "description": "whiteboard viral markets", "is_flaged": null, "project": "inbox" },
    { "id": 79, "due_date": null, "description": "embrace e-business communities", "is_flaged": null, "project": "reminders" },
    { "id": 80, "due_date": null, "description": "whiteboard value-added initiatives", "is_flaged": null, "project": "vacation" },
    { "id": 81, "due_date": null, "description": "streamline cross-platform experiences", "is_flaged": null, "project": "reminders" },
    { "id": 82, "due_date": null, "description": "brand scalable e-business", "is_flaged": null, "project": "inbox" },
    { "id": 83, "due_date": null, "description": "engineer front-end channels", "is_flaged": null, "project": "vacation" },
    { "id": 84, "due_date": "2022-11-13 19:07:43", "description": "implement viral web services", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 85, "due_date": null, "description": "matrix viral networks", "is_flaged": null, "project": "vacation" },
    { "id": 86, "due_date": null, "description": "engineer dot-com infrastructures", "is_flaged": true, "project": "vacation" },
    { "id": 87, "due_date": null, "description": "visualize revolutionary web services", "is_flaged": false, "project": "groceries" },
    { "id": 88, "due_date": null, "description": "deliver transparent e-commerce", "is_flaged": false, "project": "inbox" },
    { "id": 89, "due_date": null, "description": "extend global metrics", "is_flaged": null, "project": "reminders" },
    { "id": 90, "due_date": null, "description": "integrate intuitive metrics", "is_flaged": null, "project": "groceries" },
    { "id": 91, "due_date": null, "description": "scale frictionless platforms", "is_flaged": null, "project": "inbox" },
    { "id": 92, "due_date": null, "description": "transition wireless relationships", "is_flaged": null, "project": "vacation" },
    { "id": 93, "due_date": "2022-11-27 15:52:17", "description": "brand global e-services", "is_flaged": null, "project": "groceries" },
    { "id": 94, "due_date": null, "description": "streamline synergistic action-items", "is_flaged": null, "project": "inbox" },
    { "id": 95, "due_date": null, "description": "repurpose one-to-one schemas", "is_flaged": true, "project": "inbox" },
    { "id": 96, "due_date": null, "description": "whiteboard transparent markets", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 97, "due_date": null, "description": "whiteboard distributed synergies", "is_flaged": null, "project": "kitchen_remodel" },
    { "id": 98, "due_date": null, "description": "synthesize 24/7 channels", "is_flaged": null, "project": "inbox" },
    { "id": 99, "due_date": null, "description": "incubate leading-edge mindshare", "is_flaged": true, "project": "reminders" },
    { "id": 100, "due_date": null, "description": "streamline clicks-and-mortar users", "is_flaged": null, "project": "inbox" }]
})

export default store